### ISSUE TITLE
后端启动时报KeyError 'pattern 48 ? ? * * * * 44 89 48 not found'

### ISSUE THREAD

**Issue by SuikaXhq** [nyaoouo/GBFR-ACT#103]
Win10系统，使用的python为3.11，ACT为master最新版，游戏版本1.2.1，运行uac_start.cmd后报错。

报错信息：
> Python: can't open file 'D:\\GBFR-ACT\\3.12.0': [Errno 2] No such file or directory
Python: can't open file 'D:\\GBFR-ACT\\3.11.0': [Errno 2] No such file or directory
Found Python 3.11 64-bit at C:\Users\SuikaXhq\AppData\Local\Programs\Python\Python311\python.exe
i am in pid=55512
Traceback (most recent call last):
  File "D:\GBFR-ACT\act_ws.py", line 123, in <module>
    main()
  File "D:\GBFR-ACT\act_ws.py", line 118, in main
    process.injector.run("import act_ws;act_ws.injected_main()")
  File "D:\GBFR-ACT\gbfr_act\utils\process.py", line 175, in run
    return self.client.rpc.run(code, args, res_key, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GBFR-ACT\gbfr_act\utils\rpc.py", line 198, in func
    return self.remote_call(item, _args, _kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GBFR-ACT\gbfr_act\utils\rpc.py", line 262, in remote_call
    raise _Rpc.set_exc(*res)
KeyError: 'pattern 48 ? ? * * * * 44 89 48 not found'

**Comment by horeaper** [comment]
同样问题，昨天还能用来着。应该是和今天的1.2.1更新有关
![Untitled](https://github.com/nyaoouo/GBFR-ACT/assets/2276325/0d59d4ca-0a6f-46ca-b868-a7bce5e75a0b)

**Comment by nyaoouo** [comment]
https://github.com/nyaoouo/GBFR-ACT/commit/ba7f518549cd65f0d5d0478a4e145cfdb17d74e5 fixed
