### ISSUE TITLE
伊欧攻击技能名称

### ISSUE THREAD

**Issue by SGtwj** [nyaoouo/GBFR-ACT#11]
简单打木桩弄了下，中文版
     "7b5934ad":{//伊欧
                        "100":"x",
                        "110":"(x)x",
                        "120":"(xx)x",
                        "210":"星梦秒蓄力(y)",
                        "211":"一蓄",
                        "212":"二蓄",
                        "213":"三蓄",
                        "214":"四蓄",
                        "300":"空中x",
                        "301":"空中(x)x",
                        "302":"空中(xx)x",
                        "400":"跳跃x",
                        "410":"跳跃y",
                        "3000":"火焰",
                        "2000":"寒冰",
                        "4000":"花耀七闪",
                        "8203":"雷霆",
                    }

**Comment by nyaoouo** [comment]
加上了，感谢pr
