### ISSUE TITLE
幾個輸出分析的呈現討論

### ISSUE THREAD

**Issue by samSA0562** [nyaoouo/GBFR-ACT#13]
第一個想建議的是否能新增總傷害的圖表？
主要是目前採用 dps/分 的折線圖，但這樣在傷害呈現會有1分鐘的延遲效果(移動平均法的特色)。
或提供如下拉式選單 (Dropdown) 的方式來讓用戶自行決定要觀測什麼數據？

第二個想建議的是否能新增於玩家名稱後方顯示造成傷害在總輸出之中佔多少比例(總傷害去分割各玩家傷害)？
能更方便的了解各成員在傷害上貢獻多少，而這也應該是多數人所關心的，或是如您建議的使用扇形圖來劃分也是不錯的呈現方式。

另外兩張圖的呈現是因為個人有對html進行私自的客製化，有將 style 中的 main-2 寬度設置為80%。
以便自適應寬度，一來是方便單螢幕使用者需要使用懸浮視窗；二來是方便適應各種不同尺寸的螢幕。
如需要做簡易的自適應功能也能列入考慮。

圖1為原巴的實戰折線圖，在斜線水平時就能立刻知道當時並沒有造成任何輸出，
圖2是為了凸顯1分鐘延遲效果的測試，控制角色為黃色，在約15秒造成一次連段後就放置不輸出，可以看到約75秒時才會歸零。

另外兩張圖的呈現是因為個人有對html進行的客製化，有將 style 中的 main-2 寬度設置為80%。
以便自適應寬度，一來是方便單螢幕使用者需要使用懸浮視窗；二來是方便適應各種不同尺寸的螢幕。

![圖1](https://github.com/nyaoouo/GBFR-ACT/assets/39234565/b9c2d2ce-c029-4c7d-b858-67451a3f8977)
圖1

![圖2](https://github.com/nyaoouo/GBFR-ACT/assets/39234565/720139be-34b3-426d-bce8-83bd5ff38339)
圖2

**Comment by nyaoouo** [comment]
已添加相關功能
https://github.com/nyaoouo/GBFR-ACT/commit/a05363768b19e3ec55070b94db872bc27baacdd4
https://github.com/nyaoouo/GBFR-ACT/commit/e1d49ddb13b83e20d571bd746bdd6aac2b05f6c0
