### ISSUE TITLE
Eugen 3 grenades + 1 shot

### ISSUE THREAD

**Issue by brunolm** [nyaoouo/GBFR-ACT#14]
In game: 1,762,530
Here: 2,252,106

Is it possible to fix it?

---

Steps:
1. enter sniper mode
2. throw 3 grenades
3. shot 1 time (no charge)

Math:
- 1 shot = `(163192 + 32638) = 195830`
- 3 grenades = `(489592 + 97918) * 3 = 1762530`
- **Total**: `1958360` (in-game number)

Details:
![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/221f7f23-03c1-480f-9160-1c2f1e587a1b)

```
                    "443d46bb": { // Eugen
                       "100": "Attack",
                       "105": "Attack (Aim)",
                       "110": "Attack 1 (Melee)",
                       "111": "Attack 2 (Melee)",
                       "112": "Attack 3 (Melee)",
                       "210": "Grenade",
                       "300": "Aerial Attack",
                       "400": "Launch",
                       "410": "Aerial Barrage",
                       "1": "Sumrak",
                       "2": "Detonator",
                       "3": "Intercept",
                       "4": "Armor-Piercing Round",
                       "5": "Venom Grenade",
                       "6": "Paralyzing Bullet",
                       "8": "Disruptor"
                    },
```

105 seems to be a shot, I only shot once but it registered 4, each grenade is registering 1 shot to itself

Targets:
![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/7606442d-d254-4021-956b-89a932f2b743)

Maybe a fix would be to ignore damage done to grenades

Grenade Target ID: `022a350f`

Proposed fix:

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/9cc1e630-14b1-4754-8daf-4b736d0fa575)

```ts
                    const target_actor = get_actor_target(actor, target_idx, target_id);
                    if (!target_actor.name.startsWith('022a350f')) {
                        actor.hit += 1;
                        actor.damage += damage;
                        actor.damage_in_minute += damage;
                    }

                    if (!target_actor.name.startsWith('022a350f')) {
                        target_actor.damage += damage;
                    }
                    const action = get_actor_action(actor, flags & (1 << 15) ? -3 : action_id);
                    if (!target_actor.name.startsWith('022a350f')) {
                        action.hit += 1;
                        action.damage += damage;
                    }
```

---

Result:
![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/fcbc1c37-dc96-49d3-b3f6-f099a2464238)

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/cbd5c46f-9b64-48b2-8b07-ca60a710f5cb)

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/b8d2980e-95fb-4fac-9293-ccf87ef80146)

**Comment by nyaoouo** [comment]
thanks for your feedback, should be fixed in https://github.com/nyaoouo/GBFR-ACT/commit/c2d7142c019afdd97b6e4855baa9c1429eb0d27b
