### ISSUE TITLE
巴薩拉卡攻擊技能名稱

### ISSUE THREAD

**Issue by Alex-Lai-0717** [nyaoouo/GBFR-ACT#15]
實測了巴薩在各行為的id
對應的為繁中版的名稱

"d16cfbde":{//巴薩拉卡
"100":"普攻一段",
"110":"普攻二段",
"120":"普攻三段",
"200":"漆黑奔騰",
"400":"擊飛攻擊",
"300":"空中普攻一段",
"301":"空中普攻二段",
"302":"空中普攻三段",
"410":"落下攻擊",
"113":"一蓄一段(秒放)",
"112":"一蓄一段(蓄滿)",
"281":"一蓄二段(秒放)",
"280":"一蓄二段(蓄滿)",
"114":"一蓄一段後銜接普攻二段",
"121":"二蓄迴旋斬",
"251":"二蓄逆向迴旋斬",
"122":"二蓄一段後銜接普攻三段",
"130":"三蓄上挑",
"252":"三蓄下砸",
"1700":"獄怒",
"1200":"大鐮格羅諾斯",
"270":"大鐮格羅諾斯後蓄力",
"1600":"月食",
"1000":"恐懼營集",
"260":"恐懼營集後蓄力",
"1100":"殘暴暗影",
"1500":"覆滅之途",
}

**Comment by nyaoouo** [comment]
麻煩可以根據現有格式
https://github.com/nyaoouo/GBFR-ACT/blob/master/act_ws_texts.js#L218
修改一下嗎

**Comment by Alex-Lai-0717** [comment]
已修正

                    "d16cfbde": {//巴薩拉加
                        "100": "X",
                        "110": "（X）X",
                        "120": "（XX）X",
                        "200": "Y",
                        "400": "上挑攻擊",
                        "300": "（空中）X",
                        "301": "（空中X）X",
                        "302": "（空中XX）X",
                        "410": "（空中）Y",
                        "113": "（X）Y",
                        "112": "（X）蓄Y",
                        "114": "（XY）X",
                        "281": "（XY）Y",
                        "280": "（XY）蓄Y",
                        "121": "（XX）Y",  //蓄滿或秒放id相同
                        "122":"（XXY）X",
                        "251":"（XXY）Y",  //蓄滿或秒放id相同
                        "130": "（XXX）Y",  //蓄滿或秒放id相同
                        "252": "（XXXY）Y",  //蓄滿或秒放id相同
                        "1000":"恐懼營集",
                        "260":"（恐懼營集）Y",  //蓄滿或秒放id相同
                        "1100":"殘暴暗影",
                        "1200":"大鐮格羅諾斯",
                        "270":"（大鐮格羅諾斯）Y",  //蓄滿或秒放id相同
                        "1500":"覆滅之途",
                        "1600":"月食",
                        "1700":"獄怒",
                    },

**Comment by nyaoouo** [comment]
感謝貢獻，已添加 https://github.com/nyaoouo/GBFR-ACT/commit/f93dae8a83f10b99fd016876536115695d3ceed5
