### ISSUE TITLE
关于简体中文下菲莉技能部分显示为技能代码的问题

### ISSUE THREAD

**Issue by tanaka247652** [nyaoouo/GBFR-ACT#32]
![Z2K3SX5{Z$X66~Y54PPFKC7](https://github.com/nyaoouo/GBFR-ACT/assets/127172468/8b902c95-35b2-4f5b-a8b1-500ab248f9b5)

**Comment by xiaozeQAQ** [comment]
菲丽的简中还没写 明天我加上

**Comment by WKXiaoZe** [comment]
> 菲丽的简中还没写 明天我加上

已经添加
