### ISSUE TITLE
主控夏洛特打了一场原巴,来贡献一点ID对应的攻击名字

### ISSUE THREAD

**Issue by njjjay** [nyaoouo/GBFR-ACT#4]
</head>
<body>

"100":"X",
"101":"X",
"102":"X",
"103":"X",
"104":"X",
"105":"X",
"106":"X",
"107":"X",
"120":"YX",
"201":"耀眼猛攻?",
"1100":"?",
"1200":"跳跃反击",
"1600":"卢米埃之剑",
"1610":"卢米埃之剑终结",
"5000":"连射炮",
"5010":"蓄力炮lv1",

</body>

</html>

平砍系列我去测完再来更新

**Comment by nyaoouo** [comment]
感谢提供，可以基于 https://github.com/nyaoouo/GBFR-ACT/blob/master/act_ws_texts.js 格式整理一下吗
