### ISSUE TITLE
輸出詳情新增角色技能描述功能請求

### ISSUE THREAD

**Issue by samSA0562** [nyaoouo/GBFR-ACT#41]
因為菲莉的詞條較為特殊：
101、102為第 n+3 次蓄力後X；111、112為第 n+1 次蓄力後X；121、122為第 n+2 次蓄力後X，n為第幾次循環。
之後寵物也會共用102；112；122的詞條作為寵物攻擊詞條。
需要細部了解各個傷害統計是進行方式就需要本功能來說明。

**Comment by nyaoouo** [comment]
意思是提供tooltip或者類似控件在action表格中用於對action作註解嗎

**Comment by samSA0562** [comment]
是的，個人想法是在詳情 (dialog) 的 Tabs 中新增一欄 Tab 來放置說明。
Tab 的內容填入簡易的文本即可，
內容可以先將 act_ws_texts.js 的註解當成說明文本。
如圖示意。
![示意圖](https://github.com/nyaoouo/GBFR-ACT/assets/39234565/5b87c6d7-d0a5-4695-abbf-68016a59035f)

**Comment by nyaoouo** [comment]
實現在 https://github.com/nyaoouo/GBFR-ACT/commit/fd313b19202e528c768ac0ab60de641f7d00ffd3
數據填寫參考commit內容
![image](https://github.com/nyaoouo/GBFR-ACT/assets/64143453/9ce9d220-6353-4b42-b14e-955ad4f162de)
