### ISSUE TITLE
Katalina's Action IDs

### ISSUE THREAD

**Issue by Harkains** [nyaoouo/GBFR-ACT#5]
I can't really speak Chinese at all sadly but hopefully you can use these findings to help with the labeling for one of the characters.

| Katalina Attack       | ID    |
|-----------------------|-------|
| Normal 1              | #100  |
| Normal 2              | #101  |
| Normal 3              | #102  |
| Normal 4              | #103 (Rapid input) |
| Normal 5              | #104  |
| Launch                | #400  |
|-----------------------|-------|
| Aerial Normal         |       |
|                        | #300 (1st) |
|                        | #301 (2nd) |
|                        | #302 (3rd) |
|-----------------------|-------|
| Katalina Combo (Triangle inputs) | |
| Oathsworn Blade       | #200 (1st) |
|                        | #201 (2nd) |
|                        | #202 (3rd) |
| Finisher 1            | #110  |
| Finisher 2            | #120  |
| Finisher 3            | #130  |
| Finisher 4            | #140  |
| Aerial Barrage        | #410  |
| Aerial Finisher       | #303  |
|-----------------------|-------|
| Pactstrike  |       |
| 1st                   | #245  |
| 2nd                   | #250  |
| 3rd                   | #252  |
| 4th                   | #253  |
| 5th                   | #254  |
| 6th                   | #255  |
| 7th                   | #259  |
|-----------------------|-------|
| Katalina Skills     |       |
|  Enchanted Lands    | # 1     |
|  Winter's Rain      | # 2      |
|  Sacred Winds       | # 4     |
|  Azure Sword        | # 5      |
|  Frost Blade        | # 7    |

**Comment by Souma-Sumire** [comment]
I initiated a PR #7. If merged, you will be able to easily submit PRs for your language.

**Comment by nyaoouo** [comment]
Thanks for the data， can you format it as https://github.com/nyaoouo/GBFR-ACT/blob/master/act_ws_texts.js so that I can add it directly into the code

**Comment by Harkains** [comment]
I've never really done this before so but I've just submitted the format change for  you to look over to see if I formatted this correctly.

**Comment by nyaoouo** [comment]
> I've never really done this before so but I've just submitted the format change for you to look over to see if I formatted this correctly.

you can just reply here and i will add it to code

**Comment by Harkains** [comment]
"34d4fd8f": {
                    "100": "X",
                    "101": "（X）X",
                    "102": "（XX）X",
                    "103": "（XXX）X-X Rapid Input",
                    "104": " (XXX X~X) X",
                    "110": "（X）Y",
                    "120": "（XX）Y",
                    "130": " (XXX) Y",
                    "140": " (XXXX) Y",    
                    "200": "Y",
                    "201": "(Y) Y",
                    "202": "(YY) Y",
                    "245": "(Ares) Y1",
                    "250": "(Ares) Y2",
                    "252": "(Ares) Y3",
                    "253": "(Ares) Y4",
                    "254": "(Ares) Y5",
                    "255": "(Ares) Y6",
                    "259": "(Ares) Y7",   
                    "300": "(jump)X1",
                    "301": "(jump)X2",
                    "302": "(jump)X3",
                    "303": "(jump)(XXX) Y",
                    "400": "upward attack",
                    "410": "(jump)Y",
                    "1100": "Enchanted Lands",
                    "1200": "Winter's Rain",
                    "1400": "Sacred Winds",
                    "1500": "Azure Sword",
                    "1700": "Frost Blade",
                    },
                    
                    Like this?

**Comment by nyaoouo** [comment]
added, take a try

**Comment by Harkains** [comment]
![Ng](https://github.com/nyaoouo/GBFR-ACT/assets/114112867/2533ce2c-ecac-4a23-ad72-c8101a0cc7ba)
Doesn't seem to be working

**Comment by Harkains** [comment]
I think I might know the problem I put down the wrong ID numbers for the skills listed before so it should be

"1100": "Enchanted Lands",
"1200": "Winter's Rain",
"1400": "Sacred Winds",
"1500": "Azure Sword",
"1700": "Frost Blade",

to 

"1": "Enchanted Lands",
"2": "Winter's Rain",
"4": "Sacred Winds",
"5": "Azure Sword",
"7": "Frost Blade",

**Comment by nyaoouo** [comment]
take a try

**Comment by Harkains** [comment]
Need another correction with Katalina's ID

"245": "(Ares) Y1"

to

"243": "(Ares) Y1"

Also it seems none of the IDs for Vane or Katalina is working at all for any of the actions as I've tested for the past few hours.
