### ISSUE TITLE
Action id 0 = environment/enemy damage?

### ISSUE THREAD

**Issue by brunolm** [nyaoouo/GBFR-ACT#72]
I was testing Proto Bahamut cannons, and I saw action id 0 when destroying his orbs

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/3ab6bd37-bbb2-4969-a390-594299182e3c)

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/7d7ab4c2-11be-433b-8abe-65865604a189)

I also noticed that on Evyl Blackwyrm if you kill a small enemy and throw the orb at the boss, the boss takes damage from action 0

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/ec004494-6a40-4871-a182-3e37bed31c97)

My guess is that `0` is for "Environmental Damage" or "Enemy Damage" or something like that.

**Comment by Emptiest** [comment]
It's in another language, but this is also being discussed in #26
