### ISSUE TITLE
KeyError: 'pattern is not unique, at least 2 is found'

### ISSUE THREAD

**Issue by Swernan** [nyaoouo/GBFR-ACT#73]
环境
--
win10
2/29下载的文件
python3.11.6/3.11.8

错误描述
--
运行uac_start.cmd后返回KeyError: 'pattern is not unique, at least 2 is found'
![image](https://github.com/nyaoouo/GBFR-ACT/assets/132660346/27d51f7b-ac33-4146-9948-6f7fc95313ec)

**Comment by nyaoouo** [comment]
关掉其他挂，重新启动之后是否存在一样问题

**Comment by Swernan** [comment]
未安装logs和使用parser，重启软件、重启电脑问题同样存在

**Comment by WKXiaoZe** [comment]
新版本我也出现这个问题了XD

**Comment by nyaoouo** [comment]
别急.jpg 还在更新

**Comment by nyaoouo** [comment]
更好了应该

**Comment by WKXiaoZe** [comment]
能用了0v0

**Comment by Mayrou** [comment]
三点钟下了新的包还是出现了相同的错误

**Comment by nyaoouo** [comment]
> 三点钟下了新的包还是出现了相同的错误

请具体描述“相同的错误”，包括提供完整报错

**Comment by Mayrou** [comment]
> > 三点钟下了新的包还是出现了相同的错误
> 
> 请具体描述“相同的错误”，包括提供完整报错

同样是运行uac_start.cmd后返回KeyError: 'pattern is not unique, at least 2 is found'
![QQ图片20240314150816](https://github.com/nyaoouo/GBFR-ACT/assets/73111392/24efe8dc-fb28-4f2d-8e82-d3aeb97351b5)

**Comment by nyaoouo** [comment]
> > > 三点钟下了新的包还是出现了相同的错误
> > 
> > 
> > 请具体描述“相同的错误”，包括提供完整报错
> 
> 同样是运行uac_start.cmd后返回KeyError: 'pattern is not unique, at least 2 is found' ![QQ图片20240314150816](https://private-user-images.githubusercontent.com/73111392/312734654-24efe8dc-fb28-4f2d-8e82-d3aeb97351b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDE2ODcsIm5iZiI6MTcxMDQwMTM4NywicGF0aCI6Ii83MzExMTM5Mi8zMTI3MzQ2NTQtMjRlZmU4ZGMtZmIyOC00ZjJkLThlODItZDNhZWI5NzM1MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3Mjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGY4ZTc5MThhODRkNjZiNzNkNDk5OTg0YzYxMzVlNTc0ZjZlOTkwOWExMTg4ODcxMWUwOGMwZmEwYzMyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YlndjbICiqj2rQXBbXlfeqjWWfY0-WV6FJ8-W5Vi_A)

再更新一下，加了个报错打印，看看报错

**Comment by Mayrou** [comment]
> > > > 三点钟下了新的包还是出现了相同的错误
> > > 
> > > 
> > > 请具体描述“相同的错误”，包括提供完整报错
> > 
> > 
> > 同样是运行uac_start.cmd后返回KeyError: 'pattern is not unique, at least 2 is found' ![QQ图片20240314150816](https://private-user-images.githubusercontent.com/73111392/312734654-24efe8dc-fb28-4f2d-8e82-d3aeb97351b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDE2ODcsIm5iZiI6MTcxMDQwMTM4NywicGF0aCI6Ii83MzExMTM5Mi8zMTI3MzQ2NTQtMjRlZmU4ZGMtZmIyOC00ZjJkLThlODItZDNhZWI5NzM1MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3Mjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGY4ZTc5MThhODRkNjZiNzNkNDk5OTg0YzYxMzVlNTc0ZjZlOTkwOWExMTg4ODcxMWUwOGMwZmEwYzMyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YlndjbICiqj2rQXBbXlfeqjWWfY0-WV6FJ8-W5Vi_A)
> 
> 再更新一下，加了个报错打印，看看报错

还是同样的情况，会不会和mod有关？今天更新完上限的时候提示一些旧版本的mod用不了，但我没有去卸载
![QQ截图20240314160438](https://github.com/nyaoouo/GBFR-ACT/assets/73111392/da2ecc66-00c1-4712-9d6e-7ca1f6f7e4b9)

**Comment by nyaoouo** [comment]
> > > > > 三点钟下了新的包还是出现了相同的错误
> > > > 
> > > > 
> > > > 请具体描述“相同的错误”，包括提供完整报错
> > > 
> > > 
> > > 同样是运行uac_start.cmd后返回KeyError: 'pattern is not unique, at least 2 is found' ![QQ图片20240314150816](https://private-user-images.githubusercontent.com/73111392/312734654-24efe8dc-fb28-4f2d-8e82-d3aeb97351b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDE2ODcsIm5iZiI6MTcxMDQwMTM4NywicGF0aCI6Ii83MzExMTM5Mi8zMTI3MzQ2NTQtMjRlZmU4ZGMtZmIyOC00ZjJkLThlODItZDNhZWI5NzM1MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3Mjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGY4ZTc5MThhODRkNjZiNzNkNDk5OTg0YzYxMzVlNTc0ZjZlOTkwOWExMTg4ODcxMWUwOGMwZmEwYzMyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YlndjbICiqj2rQXBbXlfeqjWWfY0-WV6FJ8-W5Vi_A)
> > 
> > 
> > 再更新一下，加了个报错打印，看看报错
> 
> 还是同样的情况，会不会和mod有关？今天更新完上限的时候提示一些旧版本的mod用不了，但我没有去卸载 ![QQ截图20240314160438](https://private-user-images.githubusercontent.com/73111392/312750314-da2ecc66-00c1-4712-9d6e-7ca1f6f7e4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDQxOTUsIm5iZiI6MTcxMDQwMzg5NSwicGF0aCI6Ii83MzExMTM5Mi8zMTI3NTAzMTQtZGEyZWNjNjYtMDBjMS00NzEyLTlkNmUtN2NhMWY2ZjdlNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNDg3Y2M3YjVjMThiYzNkMmYwMDg0ZWI1YTJjY2UxZGI2NDYxN2RlNzg5OTlmNTFlZjI2NmY5MDM2NzgyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4BXLyC-JW6wuTkmxF4hgC-r_FUmU3ZyfbfkdPhJcBvo)

你都没更新好……

**Comment by Mayrou** [comment]
> > > > > > 三点钟下了新的包还是出现了相同的错误
> > > > > 
> > > > > 
> > > > > 请具体描述“相同的错误”，包括提供完整报错
> > > > 
> > > > 
> > > > 同样是运行uac_start.cmd后返回KeyError: 'pattern is not unique, at least 2 is found' ![QQ图片20240314150816](https://private-user-images.githubusercontent.com/73111392/312734654-24efe8dc-fb28-4f2d-8e82-d3aeb97351b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDE2ODcsIm5iZiI6MTcxMDQwMTM4NywicGF0aCI6Ii83MzExMTM5Mi8zMTI3MzQ2NTQtMjRlZmU4ZGMtZmIyOC00ZjJkLThlODItZDNhZWI5NzM1MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3Mjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGY4ZTc5MThhODRkNjZiNzNkNDk5OTg0YzYxMzVlNTc0ZjZlOTkwOWExMTg4ODcxMWUwOGMwZmEwYzMyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YlndjbICiqj2rQXBbXlfeqjWWfY0-WV6FJ8-W5Vi_A)
> > > 
> > > 
> > > 再更新一下，加了个报错打印，看看报错
> > 
> > 
> > 还是同样的情况，会不会和mod有关？今天更新完上限的时候提示一些旧版本的mod用不了，但我没有去卸载 ![QQ截图20240314160438](https://private-user-images.githubusercontent.com/73111392/312750314-da2ecc66-00c1-4712-9d6e-7ca1f6f7e4b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDQxOTUsIm5iZiI6MTcxMDQwMzg5NSwicGF0aCI6Ii83MzExMTM5Mi8zMTI3NTAzMTQtZGEyZWNjNjYtMDBjMS00NzEyLTlkNmUtN2NhMWY2ZjdlNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4MTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNDg3Y2M3YjVjMThiYzNkMmYwMDg0ZWI1YTJjY2UxZGI2NDYxN2RlNzg5OTlmNTFlZjI2NmY5MDM2NzgyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4BXLyC-JW6wuTkmxF4hgC-r_FUmU3ZyfbfkdPhJcBvo)
> 
> 你都没更新好……
是三点半下更新的包呀，我是四点钟下的，不至于还下了个旧的回来吧

**Comment by Souma-Sumire** [comment]
>  是三点半下更新的包呀，我是四点钟下的，不至于还下了个旧的回来吧

确保是在main分支下 + 不要使用奇怪的下载工具，尤其是某些国产软件

**Comment by Mayrou** [comment]
> > 是三点半下更新的包呀，我是四点钟下的，不至于还下了个旧的回来吧
> 
> 确保是在main分支下 + 不要使用奇怪的下载工具，尤其是某些国产软件

应该是mod管理器的问题，路径卸载+修复后就能恢复使用了
