### ISSUE TITLE
无法下载zip

### ISSUE THREAD

**Issue by SauronSkywalker** [nyaoouo/GBFR-ACT#74]
选择download ZIP，跳转链接404不存在，已经翻墙了，可以正常打开谷歌等页面
![QQ截图20240301170847](https://github.com/nyaoouo/GBFR-ACT/assets/59997490/01a058a8-3983-483b-a96f-6e6f42382d26)

**Comment by WKXiaoZe** [comment]
[GBFR-ACT-master (9).zip](https://github.com/nyaoouo/GBFR-ACT/files/14458886/GBFR-ACT-master.9.zip)

**Comment by SauronSkywalker** [comment]
> [GBFR-ACT-master (9).zip](https://github.com/nyaoouo/GBFR-ACT/files/14458886/GBFR-ACT-master.9.zip)

感谢
