### ISSUE TITLE
Idea: Show Session ID

### ISSUE THREAD

**Issue by brunolm** [nyaoouo/GBFR-ACT#88]
It'd be nice to see the Session ID (if you're playing online), so it makes it easier to copy the code and also to be able to group data by session id.

I'm don't know how to use these hooks properly and the data I have might not be helpful, but what I know is:

This hooks in the call when you're viewing Session Details and click to display hidden information
```py
        p_on_show_session_id, = scanner.find_val('e8 * * * * c6 ? ? ? 8B 45 fc 45 ? be c8 ? ? ? ? ? 86 d0 01 00 00 4c 89 f1 31 ?')
        print(f'p_on_show_session_id={p_on_show_session_id:#x}')
        self.on_show_session_id_hook = Hook(p_on_show_session_id, self._on_show_session_id, ctypes.c_size_t, [])
```

But it's crashing with a bunch of errors for me.

This is the pointer I found on CE that points to the hidden session code when you click to display in the session details:

![image](https://github.com/nyaoouo/GBFR-ACT/assets/706078/03351b2c-38b1-4100-a4b7-85db70ed180f)

That's all info I could get so far.

So, anyway, if you think this could be something interesting to add I'd love it! But if that doesn't make sense I understand.

Thanks!

**Comment by nyaoouo** [comment]
intresting, but is there any method to get this id any time? if this id can only found when plyer check it manully, it may cause many  misjudgment

**Comment by brunolm** [comment]
I could not find the ID at any time. I don't know how it's stored. I gave up on this, I don't know what to look for.
