### ISSUE TITLE
Cannot read index of character in Mission The Final Vision

### ISSUE THREAD

**Issue by Tanimodori** [nyaoouo/GBFR-ACT#91]
![image](https://github.com/nyaoouo/GBFR-ACT/assets/29478770/3d8a17bd-8636-4352-a6dc-51b3284fc695)
![image](https://github.com/nyaoouo/GBFR-ACT/assets/29478770/8333f749-82af-4da2-8a5b-f794066f5c59)
![image](https://github.com/nyaoouo/GBFR-ACT/assets/29478770/fc927a33-7a3b-4133-a17b-44a9187dbebe)

**Comment by Tanimodori** [comment]
This issue only appears in online sessions. The `load-party` event is skipped. Party member with an index >= 2 appears to be -1.

![image](https://github.com/nyaoouo/GBFR-ACT/assets/29478770/a910dd17-9364-4df0-a01a-f2a5e3b81a99)

**Comment by nyaoouo** [comment]
please update and try if same issue happen

**Comment by Tanimodori** [comment]
Confirmed that issue is fixed at commit 764184b. Thanks for your quick fix.
