### ISSUE TITLE
yodarha-EN

### ISSUE THREAD

**Issue by PaatL** [nyaoouo/GBFR-ACT#93]
paste this in EN-section, ty

 "PL1300": { // Yodarha
                            "desc": "Cycle (C) refers to number of times the combo has completed.",
                            "100": "X",
                            "110": "(X) X",
                            "111": "(1C) X", "111_desc": "Cycle (C) refers to number of times the combo has completed.",
                            "120": "(XX) X",
                            "121": "(2C) X", "121_desc": "Cycle (C) refers to number of times the combo has completed.",
                            "130": "(XXX) X",
                            "131": "(3C) X", "131_desc": "Cycle (C) refers to number of times the combo has completed.",
                            "140": "(XXXXX) X",
                            "141": "(4C) X", "141_desc": "Cycle (C) refers to number of times the combo has completed.",
                            "150": "Combo Finisher",
                            "151": "(1C) Combo Finisher", "151_desc": "Cycle (C)",
                            "152": "(2C) Combo Finisher", "152_desc": "Cycle (C)",
                            "153": "(3C) Combo Finisher", "153_desc": "Cycle (C)",
                            "154": "(4C) Combo Finisher", "154_desc": "Cycle (C)",
                            "201": "Y","201_desc": "Counter",
                            "300": "(jump) X",
                            "301": "(jumpX) X",
                            "302": "(jumpXX) X2",
                            "303": "(jumpXXX) X3",
                            "400": "Launch",
                            "410": "Aerial Barrage",
                            "1": "Awakening",
                            "2": "Empty Mist",
                            "5": "Tit for Tat",
                            "7": "Flashing Void",
                            "8": "Sky Shatter",
                            "17":"Flashing Void (Combo)",
                            "18":"Flashing Void (Finisher)",
                    },

**Comment by xPrinny** [comment]
I made a PR for this https://github.com/nyaoouo/GBFR-ACT/pull/94 .
